language: ruby
rvm:
  - 2.4
before_install:
  - gem update --system
  - gem install bundler
  - gem install html-proofer
script: bundle exec jekyll build && bundle exec htmlproofer --allow-hash-href ./_site
